# Generated by Django 3.1.3 on 2022-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.CharField(max_length=50)),
                ('mrating', models.CharField(max_length=50)),
                ('mrelease', models.CharField(max_length=50)),
                ('mid', models.IntegerField()),
                ('mgeneres', models.CharField(max_length=100)),
            ],
        ),
    ]
