# Generated by Django 3.1.3 on 2022-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mrelease',
            field=models.TextField(),
        ),
    ]
